
networks:
  stock-net:
    driver: bridge

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    networks:
      - stock-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    networks:
      - stock-net
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  redis:
    image: redis:7.2-alpine
    container_name: redis
    networks:
      - stock-net
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    networks:
      - stock-net
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-storage:/var/lib/grafana

  spark:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark
    networks:
      - stock-net
    ports:
      - "4040:4040"
    environment:
      - SPARK_NO_DAEMONIZE=true
    user: root
    volumes:
      - ./spark-app:/opt/spark-app
    command: tail -f /dev/null

volumes:
  grafana-storage: